//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelFirst_Test
    {
        public ModelFirst_Test()
        {
            this.ModelFirst_TestFirst = new HashSet<ModelFirst_TestFirst>();
        }
    
        public int Id { get; set; }
        public string StudentName { get; set; }
    
        public virtual ICollection<ModelFirst_TestFirst> ModelFirst_TestFirst { get; set; }
    }
}
