//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFirstAppContainer : DbContext
    {
        public ModelFirstAppContainer()
            : base("name=ModelFirstAppContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ModelFirst_Test> ModelFirst_Test { get; set; }
        public virtual DbSet<ModelFirst_TestFirst> ModelFirst_TestFirst { get; set; }
    }
}
