//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelFirst_TestFirst
    {
        public int Id { get; set; }
        public string ClassName { get; set; }
        public int ModelFirst_TestId { get; set; }
    
        public virtual ModelFirst_Test ModelFirst_Test { get; set; }
    }
}
