//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField.FormWihtMasterPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstOrganization
    {
        public int OrgCode { get; set; }
        public Nullable<int> OrgCodeOth { get; set; }
        public Nullable<int> OrgCityCode { get; set; }
        public string OrgName { get; set; }
        public string ContactPer1Name { get; set; }
        public string ContactPer1Mobile { get; set; }
        public string ContactPer1Email { get; set; }
        public string ContactPer2Name { get; set; }
        public string ContactPer2Mobile { get; set; }
        public string ContactPer2Email { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string AgreementNo { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
