//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField.FormWihtMasterPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUser
    {
        public int UserCode { get; set; }
        public Nullable<int> UserCodeOdp { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public string UserLoginId { get; set; }
        public string UserLoginPass { get; set; }
        public Nullable<int> UserEmpCode { get; set; }
        public Nullable<int> OrgCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> EntryUserCode { get; set; }
        public Nullable<int> UserSubLevelCode { get; set; }
        public string UserName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string AadhaarNo { get; set; }
        public Nullable<int> DeptCode { get; set; }
        public Nullable<int> SubDeptCode { get; set; }
        public Nullable<int> Desgcode { get; set; }
    }
}
