//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField.FormWihtMasterPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Manufacturer { get; set; }
        public string ShippingNo { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string BatchNo { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
