//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicField.FormWihtMasterPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_State
    {
        public int State_Id { get; set; }
        public string State_Name { get; set; }
        public Nullable<int> Country_Id { get; set; }
    }
}
