// <auto-generated />
namespace dynamicField.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addPL_SecondClassClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPL_SecondClassClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202207020944251_addPL_SecondClassClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
