// <auto-generated />
namespace dynamicField.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addPL_ThirdClassClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPL_ThirdClassClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202207020947068_addPL_ThirdClassClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
